// <auto-generated />
namespace Shopee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update08111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update08111));
        
        string IMigrationMetadata.Id
        {
            get { return "202311080409082_Update08111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
